# fly.toml app configuration file generated for project2crisignacio on 2023-05-19T09:52:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "project2crisignacio"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
